
export const  restaurants = [
    {
        id: 1,
        name: "Spice Villa",
        location: "Luton Street",
        area: "London",
        openTime: "10:00 AM",
        closeTime: "11:00 PM",
        isOpen: true,
        rating: 4.5,
        totalRatings: 1240,
        priceForTwo: 25,
        cuisine: ["Indian", "North Indian"],
        speciality: 'Dal bati',
        deliveryTime: "30-35 mins",
        distance: "2.1 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 20% OFF",
        isVeg: true,
        isPopular: true
    },
    {
        id: 2,
        name: "Urban Tadka",
        location: "Regent Street",
        area: "London",
        openTime: "9:00 AM",
        closeTime: "10:30 PM",
        isOpen: true,
        rating: 4.2,
        totalRatings: 980,
        priceForTwo: 30,
        cuisine: ["Indian", "Punjabi"],
        speciality: 'Jalebi fafada',
        deliveryTime: "25-30 mins",
        distance: "1.5 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Buy 1 Get 1",
        isVeg: false,
        isPopular: true
    },
    {
        id: 3,
        name: "Green Bowl",
        location: "Oxford Road",
        area: "London",
        openTime: "11:00 AM",
        closeTime: "9:00 PM",
        isOpen: true,
        rating: 4.7,
        totalRatings: 1560,
        priceForTwo: 22,
        cuisine: ["Healthy", "Salads"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "20-25 mins",
        distance: "1.2 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Delivery",
        isVeg: true,
        isPopular: true
    },
    {
        id: 4,
        name: "Burger Hub",
        location: "Baker Street",
        area: "London",
        openTime: "12:00 PM",
        closeTime: "12:00 AM",
        isOpen: true,
        rating: 4.1,
        totalRatings: 840,
        priceForTwo: 28,
        cuisine: ["Burgers", "Fast Food"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "30-40 mins",
        distance: "3.0 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 15% OFF",
        isVeg: false,
        isPopular: false
    },
    {
        id: 5,
        name: "Pasta Point",
        location: "Camden Market",
        area: "London",
        openTime: "10:30 AM",
        closeTime: "10:00 PM",
        isOpen: true,
        rating: 4.3,
        totalRatings: 670,
        priceForTwo: 35,
        cuisine: ["Italian", "Pasta"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "35-40 mins",
        distance: "4.2 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Combo Deals",
        isVeg: true,
        isPopular: false
    },
    {
        id: 6,
        name: "Dragon Wok",
        location: "Soho",
        area: "London",
        openTime: "11:30 AM",
        closeTime: "11:30 PM",
        isOpen: true,
        rating: 4.6,
        totalRatings: 1890,
        priceForTwo: 32,
        cuisine: ["Chinese", "Asian"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "25-30 mins",
        distance: "2.8 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 25% OFF",
        isVeg: false,
        isPopular: true
    },
    {
        id: 7,
        name: "Tandoori Flames",
        location: "King's Cross",
        area: "London",
        openTime: "12:00 PM",
        closeTime: "11:00 PM",
        isOpen: true,
        rating: 4.4,
        totalRatings: 1120,
        priceForTwo: 40,
        cuisine: ["Indian", "Tandoor"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "35-45 mins",
        distance: "3.6 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Dessert",
        isVeg: false,
        isPopular: true
    },
    {
        id: 8,
        name: "Sushi Zen",
        location: "Canary Wharf",
        area: "London",
        openTime: "11:00 AM",
        closeTime: "10:00 PM",
        isOpen: true,
        rating: 4.8,
        totalRatings: 920,
        priceForTwo: 50,
        cuisine: ["Japanese", "Sushi"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "40-45 mins",
        distance: "5.1 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Chef’s Special",
        isVeg: false,
        isPopular: true
    },
    {
        id: 9,
        name: "Street Momos",
        location: "Whitechapel",
        area: "London",
        openTime: "4:00 PM",
        closeTime: "11:30 PM",
        isOpen: true,
        rating: 4.0,
        totalRatings: 430,
        priceForTwo: 15,
        cuisine: ["Street Food", "Momos"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "20-25 mins",
        distance: "1.0 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 10% OFF",
        isVeg: true,
        isPopular: false
    },
    {
        id: 10,
        name: "Royal Biryani",
        location: "Southall",
        area: "London",
        openTime: "11:00 AM",
        closeTime: "12:00 AM",
        isOpen: true,
        rating: 4.5,
        totalRatings: 2100,
        priceForTwo: 38,
        cuisine: ["Biryani", "Hyderabadi"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "35-40 mins",
        distance: "4.8 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Extra Raita Free",
        isVeg: false,
        isPopular: true
    },
    {
        id: 11,
        name: "Veg Delight",
        location: "Greenwich",
        area: "London",
        openTime: "9:00 AM",
        closeTime: "9:30 PM",
        isOpen: true,
        rating: 4.6,
        totalRatings: 780,
        priceForTwo: 20,
        cuisine: ["Pure Veg", "Indian"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "25-30 mins",
        distance: "2.4 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 15% OFF",
        isVeg: true,
        isPopular: false
    },
    {
        id: 12,
        name: "BBQ Nation Express",
        location: "Stratford",
        area: "London",
        openTime: "12:00 PM",
        closeTime: "11:00 PM",
        isOpen: true,
        rating: 4.3,
        totalRatings: 1650,
        priceForTwo: 45,
        cuisine: ["BBQ", "Grill"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "40-50 mins",
        distance: "5.6 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Weekend Special",
        isVeg: false,
        isPopular: true
    },
    {
        id: 13,
        name: "Cafe Mocha",
        location: "Chelsea",
        area: "London",
        openTime: "8:00 AM",
        closeTime: "10:00 PM",
        isOpen: true,
        rating: 4.4,
        totalRatings: 1340,
        priceForTwo: 18,
        cuisine: ["Cafe", "Beverages"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "15-20 mins",
        distance: "1.3 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Cookie",
        isVeg: true,
        isPopular: true
    },
    {
        id: 14,
        name: "Pizza Crust",
        location: "Hammersmith",
        area: "London",
        openTime: "11:00 AM",
        closeTime: "11:00 PM",
        isOpen: true,
        rating: 4.1,
        totalRatings: 960,
        priceForTwo: 28,
        cuisine: ["Pizza", "Italian"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "30-35 mins",
        distance: "3.3 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 20% OFF",
        isVeg: false,
        isPopular: false
    },
    {
        id: 15,
        name: "Falafel House",
        location: "Paddington",
        area: "London",
        openTime: "10:00 AM",
        closeTime: "9:00 PM",
        isOpen: true,
        rating: 4.7,
        totalRatings: 520,
        priceForTwo: 22,
        cuisine: ["Middle Eastern", "Vegan"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "20-25 mins",
        distance: "1.8 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Hummus",
        isVeg: true,
        isPopular: true
    },
    {
        id: 16,
        name: "Kebab Junction",
        location: "Ilford",
        area: "London",
        openTime: "1:00 PM",
        closeTime: "12:00 AM",
        isOpen: true,
        rating: 4.0,
        totalRatings: 710,
        priceForTwo: 26,
        cuisine: ["Kebab", "Fast Food"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "30-35 mins",
        distance: "4.0 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Late Night Deals",
        isVeg: false,
        isPopular: false
    },
    {
        id: 17,
        name: "South Spice",
        location: "Wembley",
        area: "London",
        openTime: "9:00 AM",
        closeTime: "10:00 PM",
        isOpen: true,
        rating: 4.5,
        totalRatings: 1380,
        priceForTwo: 27,
        cuisine: ["South Indian", "Dosa"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "25-30 mins",
        distance: "3.9 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Filter Coffee",
        isVeg: true,
        isPopular: true
    },
    {
        id: 18,
        name: "The Dessert Jar",
        location: "Shoreditch",
        area: "London",
        openTime: "12:00 PM",
        closeTime: "11:00 PM",
        isOpen: true,
        rating: 4.8,
        totalRatings: 860,
        priceForTwo: 20,
        cuisine: ["Desserts", "Bakery"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "20-25 mins",
        distance: "2.0 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 15% OFF",
        isVeg: true,
        isPopular: true
    },
    {
        id: 19,
        name: "Mexi Bowl",
        location: "Croydon",
        area: "London",
        openTime: "11:00 AM",
        closeTime: "10:30 PM",
        isOpen: true,
        rating: 4.2,
        totalRatings: 490,
        priceForTwo: 24,
        cuisine: ["Mexican", "Bowls"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "30-35 mins",
        distance: "4.6 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Free Nachos",
        isVeg: false,
        isPopular: false
    },
    {
        id: 20,
        name: "Cloud Kitchen Co.",
        location: "Hackney",
        area: "London",
        openTime: "12:00 PM",
        closeTime: "12:00 AM",
        isOpen: true,
        rating: 4.6,
        totalRatings: 1040,
        priceForTwo: 29,
        cuisine: ["Multi-cuisine"],
        speciality: 'idle, dosa, samber',
        deliveryTime: "25-30 mins",
        distance: "2.7 km",
        image: "/assets/360_F_758266271_yksdY7RLYIIY6jofjJorjylEDOvgcuze.jpg",
        offers: "Flat 30% OFF",
        isVeg: false,
        isPopular: true
    }
]